"""
Seed sản phẩm mẫu cho 3 loại: sách, đồ điện tử, thời trang.
Đồ điện tử gồm: laptop, điện thoại, tai nghe bluetooth.
Chạy: docker-compose exec product-service python manage.py seed_products
"""
import os
import requests
from django.core.management.base import BaseCommand
from products.models import Product, Book, Electronics, Fashion

CATALOG_SERVICE_URL = os.environ.get('CATALOG_SERVICE_URL', 'http://catalog-service:8000')

# ─────────────────────────────────────────────────────────────────────────────
# SÁCH
# Catalog: Lập trình(1), Khoa học(2), Kinh tế(3), Văn học VN(4),
#          Văn học NN(5), Kỹ năng(6), Lịch sử(7)
# ─────────────────────────────────────────────────────────────────────────────
BOOKS_DATA = [
    # Lập trình & Công nghệ
    {"catalog_name": "Lập trình & Công nghệ",
     "name": "Python Crash Course (3rd Edition)", "price": 280000, "stock": 50,
     "image_url": "https://covers.openlibrary.org/b/isbn/9781718502703-M.jpg",
     "description": "Sách học Python từ cơ bản đến nâng cao, có bài tập thực hành.",
     "book": {"author": "Eric Matthes", "publisher": "No Starch Press",
              "isbn": "9781718502703", "pages": 552, "language": "Tiếng Anh", "published_year": 2023}},
    {"catalog_name": "Lập trình & Công nghệ",
     "name": "Clean Code - Mã sạch", "price": 199000, "stock": 30,
     "description": "Hướng dẫn viết code sạch, dễ bảo trì theo tiêu chuẩn chuyên nghiệp.",
     "book": {"author": "Robert C. Martin", "publisher": "NXB Lao Động",
              "isbn": "9786045659501", "pages": 431, "language": "Tiếng Việt", "published_year": 2021}},
    {"catalog_name": "Lập trình & Công nghệ",
     "name": "Học Machine Learning với Python", "price": 249000, "stock": 40,
     "description": "Từ hồi quy tuyến tính đến deep learning, có code thực hành.",
     "book": {"author": "Aurélien Géron", "publisher": "NXB Khoa học Kỹ thuật",
              "pages": 740, "language": "Tiếng Việt"}},
    {"catalog_name": "Lập trình & Công nghệ",
     "name": "JavaScript: The Good Parts", "price": 185000, "stock": 25,
     "description": "Phần tinh hoa của ngôn ngữ JavaScript, dành cho developer muốn code tốt hơn.",
     "book": {"author": "Douglas Crockford", "publisher": "O'Reilly",
              "pages": 176, "language": "Tiếng Anh"}},
    {"catalog_name": "Lập trình & Công nghệ",
     "name": "Thiết kế hệ thống phần mềm", "price": 320000, "stock": 35,
     "description": "System design cho software engineers, từ basic đến distributed systems.",
     "book": {"author": "Alex Xu", "publisher": "NXB Trẻ",
              "pages": 400, "language": "Tiếng Việt"}},
    {"catalog_name": "Lập trình & Công nghệ",
     "name": "Docker & Kubernetes thực chiến", "price": 265000, "stock": 20,
     "description": "Containerization và orchestration cho ứng dụng production.",
     "book": {"author": "Nigel Poulton", "publisher": "NXB Khoa học Kỹ thuật",
              "pages": 320, "language": "Tiếng Việt", "published_year": 2022}},
    # Khoa học & Tự nhiên
    {"catalog_name": "Khoa học & Tự nhiên",
     "name": "Lược sử thời gian", "price": 135000, "stock": 60,
     "description": "Từ Big Bang đến lỗ đen, vũ trụ học giải thích dễ hiểu.",
     "book": {"author": "Stephen Hawking", "publisher": "NXB Trẻ",
              "pages": 232, "language": "Tiếng Việt"}},
    {"catalog_name": "Khoa học & Tự nhiên",
     "name": "Sapiens: Lược sử loài người", "price": 168000, "stock": 80,
     "description": "Lịch sử 70.000 năm của loài người qua góc nhìn khoa học.",
     "book": {"author": "Yuval Noah Harari", "publisher": "NXB Tri Thức",
              "pages": 559, "language": "Tiếng Việt"}},
    {"catalog_name": "Khoa học & Tự nhiên",
     "name": "Vũ trụ trong vỏ hạt dẻ", "price": 145000, "stock": 45,
     "description": "Stephen Hawking giải thích vật lý lý thuyết bằng hình ảnh trực quan.",
     "book": {"author": "Stephen Hawking", "publisher": "NXB Trẻ",
              "pages": 224, "language": "Tiếng Việt"}},
    {"catalog_name": "Khoa học & Tự nhiên",
     "name": "Homo Deus: Lược sử tương lai", "price": 155000, "stock": 50,
     "description": "Tương lai của nhân loại trong thời đại AI và công nghệ sinh học.",
     "book": {"author": "Yuval Noah Harari", "publisher": "NXB Tri Thức",
              "pages": 528, "language": "Tiếng Việt"}},
    # Kinh tế & Kinh doanh
    {"catalog_name": "Kinh tế & Kinh doanh",
     "name": "Đắc nhân tâm", "price": 90000, "stock": 100,
     "description": "Nghệ thuật giao tiếp và tạo dựng mối quan hệ, bestseller mọi thời đại.",
     "book": {"author": "Dale Carnegie", "publisher": "NXB Tổng hợp TP.HCM",
              "pages": 320, "language": "Tiếng Việt"}},
    {"catalog_name": "Kinh tế & Kinh doanh",
     "name": "Zero to One", "price": 125000, "stock": 45,
     "description": "Peter Thiel chia sẻ về xây dựng startup từ con số không.",
     "book": {"author": "Peter Thiel", "publisher": "NXB Trẻ",
              "pages": 256, "language": "Tiếng Việt"}},
    {"catalog_name": "Kinh tế & Kinh doanh",
     "name": "Khởi nghiệp tinh gọn", "price": 112000, "stock": 60,
     "description": "Phương pháp Lean Startup - xây dựng sản phẩm nhanh và hiệu quả.",
     "book": {"author": "Eric Ries", "publisher": "NXB Lao Động Xã Hội",
              "pages": 336, "language": "Tiếng Việt"}},
    {"catalog_name": "Kinh tế & Kinh doanh",
     "name": "Tư duy nhanh và chậm", "price": 148000, "stock": 55,
     "description": "Daniel Kahneman khám phá hai hệ thống tư duy của con người.",
     "book": {"author": "Daniel Kahneman", "publisher": "NXB Thế Giới",
              "pages": 544, "language": "Tiếng Việt"}},
    # Văn học trong nước
    {"catalog_name": "Văn học trong nước",
     "name": "Số đỏ", "price": 75000, "stock": 70,
     "description": "Tiểu thuyết trào phúng kinh điển của văn học Việt Nam.",
     "book": {"author": "Vũ Trọng Phụng", "publisher": "NXB Văn học",
              "pages": 264, "language": "Tiếng Việt", "published_year": 1936}},
    {"catalog_name": "Văn học trong nước",
     "name": "Tắt đèn", "price": 68000, "stock": 55,
     "description": "Cuộc sống bần cùng của nông dân Việt Nam trước Cách mạng tháng Tám.",
     "book": {"author": "Ngô Tất Tố", "publisher": "NXB Văn học",
              "pages": 192, "language": "Tiếng Việt"}},
    {"catalog_name": "Văn học trong nước",
     "name": "Mắt biếc", "price": 85000, "stock": 80,
     "description": "Câu chuyện tình đẹp buồn của Nguyễn Nhật Ánh.",
     "book": {"author": "Nguyễn Nhật Ánh", "publisher": "NXB Trẻ",
              "pages": 272, "language": "Tiếng Việt", "published_year": 1990}},
    # Văn học nước ngoài
    {"catalog_name": "Văn học nước ngoài",
     "name": "Nhà giả kim", "price": 88000, "stock": 90,
     "description": "Hành trình theo đuổi ước mơ của Santiago.",
     "book": {"author": "Paulo Coelho", "publisher": "NXB Hội Nhà Văn",
              "pages": 228, "language": "Tiếng Việt"}},
    {"catalog_name": "Văn học nước ngoài",
     "name": "1984", "price": 105000, "stock": 65,
     "description": "Dystopia kinh điển của George Orwell về xã hội toàn trị.",
     "book": {"author": "George Orwell", "publisher": "NXB Hội Nhà Văn",
              "pages": 328, "language": "Tiếng Việt", "published_year": 1949}},
    {"catalog_name": "Văn học nước ngoài",
     "name": "Hoàng tử bé", "price": 62000, "stock": 120,
     "description": "Truyện ngắn kinh điển về tuổi thơ và sự trong sáng.",
     "book": {"author": "Antoine de Saint-Exupéry", "publisher": "NXB Kim Đồng",
              "pages": 96, "language": "Tiếng Việt"}},
    # Kỹ năng sống
    {"catalog_name": "Kỹ năng sống",
     "name": "7 thói quen hiệu quả", "price": 118000, "stock": 85,
     "description": "Stephen Covey chia sẻ 7 thói quen của người thành công.",
     "book": {"author": "Stephen R. Covey", "publisher": "NXB Tổng hợp TP.HCM",
              "pages": 432, "language": "Tiếng Việt"}},
    {"catalog_name": "Kỹ năng sống",
     "name": "Người bán hàng vĩ đại nhất thế giới", "price": 95000, "stock": 70,
     "description": "Og Mandino - nghệ thuật bán hàng và thái độ sống tích cực.",
     "book": {"author": "Og Mandino", "publisher": "NXB Lao Động Xã Hội",
              "pages": 192, "language": "Tiếng Việt"}},
    # Lịch sử & Địa lý
    {"catalog_name": "Lịch sử & Địa lý",
     "name": "Việt Nam sử lược", "price": 128000, "stock": 40,
     "description": "Tóm tắt lịch sử Việt Nam từ thời dựng nước đến hiện đại.",
     "book": {"author": "Trần Trọng Kim", "publisher": "NXB Văn học",
              "pages": 448, "language": "Tiếng Việt"}},
    {"catalog_name": "Lịch sử & Địa lý",
     "name": "Địa lý du lịch Việt Nam", "price": 145000, "stock": 30,
     "description": "Khám phá địa lý, văn hóa và điểm du lịch 63 tỉnh thành Việt Nam.",
     "book": {"author": "Nhiều tác giả", "publisher": "NXB Giáo dục",
              "pages": 512, "language": "Tiếng Việt"}},
]

# ─────────────────────────────────────────────────────────────────────────────
# ĐỒ ĐIỆN TỬ
# Catalog: Laptop Gaming, Laptop Văn phòng, Laptop Đồ họa, Laptop Sinh viên,
#          MacBook, Điện thoại, Tai nghe Bluetooth, Phụ kiện điện tử
# subcategory: laptop | phone | headphone
# specs: dict linh hoạt theo từng loại
# ─────────────────────────────────────────────────────────────────────────────
ELECTRONICS_DATA = [

    # ── LAPTOP GAMING ────────────────────────────────────────────────────────
    {"catalog_name": "Laptop Gaming", "subcategory": "laptop",
     "name": "ASUS ROG Strix G16 2024", "price": 35990000, "stock": 15,
     "description": "Laptop gaming hiệu năng cao RTX 4070, màn hình QHD+ 240Hz.",
     "electronics": {"brand": "ASUS", "warranty_months": 24,
                     "specs": {"cpu": "Intel Core i9-14900HX", "ram": "16GB DDR5",
                               "storage": "1TB SSD NVMe", "display": "16\" QHD+ 240Hz",
                               "gpu": "RTX 4070 8GB", "battery": "90Wh",
                               "weight_kg": 2.5, "os": "Windows 11 Home"}}},
    {"catalog_name": "Laptop Gaming", "subcategory": "laptop",
     "name": "ASUS ROG Zephyrus G14 2024", "price": 42990000, "stock": 10,
     "description": "Laptop gaming mỏng nhẹ OLED 2.8K, Ryzen 9 8945HS.",
     "electronics": {"brand": "ASUS", "warranty_months": 24,
                     "specs": {"cpu": "AMD Ryzen 9 8945HS", "ram": "32GB LPDDR5X",
                               "storage": "1TB SSD", "display": "14\" 2.8K 120Hz OLED",
                               "gpu": "RTX 4070 8GB", "battery": "73Wh",
                               "weight_kg": 1.65, "os": "Windows 11 Home"}}},
    {"catalog_name": "Laptop Gaming", "subcategory": "laptop",
     "name": "ASUS TUF Gaming F15 2024", "price": 22990000, "stock": 20,
     "description": "Laptop gaming bền bỉ, RTX 4060, tản nhiệt tốt.",
     "electronics": {"brand": "ASUS", "warranty_months": 24,
                     "specs": {"cpu": "Intel Core i7-13620H", "ram": "16GB DDR5",
                               "storage": "512GB SSD", "display": "15.6\" FHD 144Hz",
                               "gpu": "RTX 4060 8GB", "battery": "90Wh",
                               "weight_kg": 2.2, "os": "Windows 11 Home"}}},
    {"catalog_name": "Laptop Gaming", "subcategory": "laptop",
     "name": "MSI Katana 15 B13VGK", "price": 26990000, "stock": 12,
     "description": "MSI gaming laptop RTX 4070, thiết kế đẹp, màn hình 144Hz.",
     "electronics": {"brand": "MSI", "warranty_months": 12,
                     "specs": {"cpu": "Intel Core i7-13620H", "ram": "16GB DDR5",
                               "storage": "1TB SSD", "display": "15.6\" FHD 144Hz",
                               "gpu": "RTX 4070 8GB", "battery": "53.5Wh",
                               "weight_kg": 2.2, "os": "Windows 11 Home"}}},
    {"catalog_name": "Laptop Gaming", "subcategory": "laptop",
     "name": "MSI Raider GE78 HX 2024", "price": 62990000, "stock": 5,
     "description": "Laptop gaming flagship MSI, RTX 4090 và màn hình QHD+ 240Hz.",
     "electronics": {"brand": "MSI", "warranty_months": 24,
                     "specs": {"cpu": "Intel Core i9-14900HX", "ram": "64GB DDR5",
                               "storage": "2TB SSD", "display": "17\" QHD+ 240Hz",
                               "gpu": "RTX 4090 16GB", "battery": "99.9Wh",
                               "weight_kg": 3.1, "os": "Windows 11 Home"}}},
    {"catalog_name": "Laptop Gaming", "subcategory": "laptop",
     "name": "Acer Nitro 5 AN515 2024", "price": 18990000, "stock": 25,
     "description": "Laptop gaming giá tốt RTX 4050, phù hợp game FHD.",
     "electronics": {"brand": "Acer", "warranty_months": 12,
                     "specs": {"cpu": "Intel Core i5-13500H", "ram": "16GB DDR5",
                               "storage": "512GB SSD", "display": "15.6\" FHD 144Hz",
                               "gpu": "RTX 4050 6GB", "battery": "57.5Wh",
                               "weight_kg": 2.2, "os": "Windows 11 Home"}}},
    {"catalog_name": "Laptop Gaming", "subcategory": "laptop",
     "name": "Acer Predator Helios Neo 16 2024", "price": 32990000, "stock": 10,
     "description": "Acer Predator RTX 4070, màn hình WUXGA 165Hz.",
     "electronics": {"brand": "Acer", "warranty_months": 12,
                     "specs": {"cpu": "Intel Core i7-14650HX", "ram": "16GB DDR5",
                               "storage": "1TB SSD", "display": "16\" WUXGA 165Hz",
                               "gpu": "RTX 4070 8GB", "battery": "90Wh",
                               "weight_kg": 2.6, "os": "Windows 11 Home"}}},
    {"catalog_name": "Laptop Gaming", "subcategory": "laptop",
     "name": "Dell Gaming G15 5530", "price": 24990000, "stock": 18,
     "description": "Laptop gaming Dell RTX 4060, màn hình 165Hz mượt mà.",
     "electronics": {"brand": "Dell", "warranty_months": 12,
                     "specs": {"cpu": "Intel Core i7-13650HX", "ram": "16GB DDR5",
                               "storage": "512GB SSD", "display": "15.6\" FHD 165Hz",
                               "gpu": "RTX 4060 8GB", "battery": "86Wh",
                               "weight_kg": 2.4, "os": "Windows 11 Home"}}},
    {"catalog_name": "Laptop Gaming", "subcategory": "laptop",
     "name": "Lenovo Legion 5i Gen 9 2024", "price": 29990000, "stock": 14,
     "description": "Lenovo Legion 5i gaming laptop RTX 4060, pin 80Wh.",
     "electronics": {"brand": "Lenovo", "warranty_months": 12,
                     "specs": {"cpu": "Intel Core i7-14650HX", "ram": "16GB DDR5",
                               "storage": "512GB SSD", "display": "15.6\" FHD 165Hz",
                               "gpu": "RTX 4060 8GB", "battery": "80Wh",
                               "weight_kg": 2.4, "os": "Windows 11 Home"}}},
    {"catalog_name": "Laptop Gaming", "subcategory": "laptop",
     "name": "Lenovo LOQ 15IAX9 2024", "price": 19990000, "stock": 20,
     "description": "Laptop gaming Lenovo giá hợp lý cho học sinh sinh viên.",
     "electronics": {"brand": "Lenovo", "warranty_months": 12,
                     "specs": {"cpu": "Intel Core i5-12450HX", "ram": "16GB DDR5",
                               "storage": "512GB SSD", "display": "15.6\" FHD 144Hz",
                               "gpu": "RTX 4050 6GB", "battery": "60Wh",
                               "weight_kg": 2.4, "os": "Windows 11 Home"}}},
    {"catalog_name": "Laptop Gaming", "subcategory": "laptop",
     "name": "HP Omen 16 2024", "price": 33990000, "stock": 10,
     "description": "HP Omen gaming laptop RTX 4070, màn hình QHD 165Hz.",
     "electronics": {"brand": "HP", "warranty_months": 12,
                     "specs": {"cpu": "AMD Ryzen 7 8845HS", "ram": "16GB DDR5",
                               "storage": "1TB SSD", "display": "16\" QHD 165Hz",
                               "gpu": "RTX 4070 8GB", "battery": "83Wh",
                               "weight_kg": 2.45, "os": "Windows 11 Home"}}},
    {"catalog_name": "Laptop Gaming", "subcategory": "laptop",
     "name": "Razer Blade 15 2024", "price": 55990000, "stock": 5,
     "description": "Laptop gaming cao cấp Razer, thiết kế mỏng nhẹ nhất phân khúc.",
     "electronics": {"brand": "Razer", "warranty_months": 12,
                     "specs": {"cpu": "Intel Core i9-14900HX", "ram": "32GB DDR5",
                               "storage": "1TB SSD", "display": "15.6\" QHD 240Hz OLED",
                               "gpu": "RTX 4080 12GB", "battery": "95.2Wh",
                               "weight_kg": 2.01, "os": "Windows 11 Home"}}},

    # ── LAPTOP VĂN PHÒNG ─────────────────────────────────────────────────────
    {"catalog_name": "Laptop Văn phòng", "subcategory": "laptop",
     "name": "Dell XPS 13 Plus 9320", "price": 32990000, "stock": 12,
     "description": "Laptop văn phòng cao cấp mỏng nhẹ, màn hình OLED cảm ứng.",
     "electronics": {"brand": "Dell", "warranty_months": 12,
                     "specs": {"cpu": "Intel Core i7-1260P", "ram": "16GB LPDDR5",
                               "storage": "512GB SSD", "display": "13.4\" FHD+ OLED Touch",
                               "battery": "55Wh", "weight_kg": 1.26, "os": "Windows 11 Pro"}}},
    {"catalog_name": "Laptop Văn phòng", "subcategory": "laptop",
     "name": "Dell Latitude 5540 Business", "price": 28990000, "stock": 10,
     "description": "Laptop doanh nghiệp Dell, bảo mật TPM 2.0, chứng nhận MIL-STD.",
     "electronics": {"brand": "Dell", "warranty_months": 36,
                     "specs": {"cpu": "Intel Core i7-1365U", "ram": "16GB DDR4",
                               "storage": "512GB SSD", "display": "15.6\" FHD IPS",
                               "battery": "54Wh", "weight_kg": 1.78, "os": "Windows 11 Pro"}}},
    {"catalog_name": "Laptop Văn phòng", "subcategory": "laptop",
     "name": "HP EliteBook 840 G10", "price": 28990000, "stock": 15,
     "description": "Laptop doanh nghiệp bảo mật cao, pin 17 giờ.",
     "electronics": {"brand": "HP", "warranty_months": 36,
                     "specs": {"cpu": "Intel Core i7-1355U", "ram": "16GB DDR5",
                               "storage": "512GB SSD", "display": "14\" FHD IPS",
                               "battery": "51Wh", "weight_kg": 1.35, "os": "Windows 11 Pro"}}},
    {"catalog_name": "Laptop Văn phòng", "subcategory": "laptop",
     "name": "HP Spectre x360 14 2024", "price": 38990000, "stock": 8,
     "description": "Laptop 2-in-1 cao cấp HP, OLED cảm ứng, thiết kế sang trọng.",
     "electronics": {"brand": "HP", "warranty_months": 12,
                     "specs": {"cpu": "Intel Core Ultra 7 155H", "ram": "16GB LPDDR5",
                               "storage": "1TB SSD", "display": "14\" 2.8K OLED Touch",
                               "battery": "72Wh", "weight_kg": 1.58, "os": "Windows 11 Home"}}},
    {"catalog_name": "Laptop Văn phòng", "subcategory": "laptop",
     "name": "Lenovo ThinkPad X1 Carbon Gen 11", "price": 38990000, "stock": 8,
     "description": "ThinkPad cao cấp nhất, siêu mỏng 1.12kg, màn hình 2K IPS.",
     "electronics": {"brand": "Lenovo", "warranty_months": 36,
                     "specs": {"cpu": "Intel Core i7-1365U", "ram": "16GB LPDDR5",
                               "storage": "512GB SSD", "display": "14\" 2K IPS",
                               "battery": "57Wh", "weight_kg": 1.12, "os": "Windows 11 Pro"}}},
    {"catalog_name": "Laptop Văn phòng", "subcategory": "laptop",
     "name": "Lenovo ThinkPad E14 Gen 5", "price": 21990000, "stock": 15,
     "description": "ThinkPad doanh nghiệp tầm trung, bàn phím tốt, bền bỉ.",
     "electronics": {"brand": "Lenovo", "warranty_months": 12,
                     "specs": {"cpu": "AMD Ryzen 5 7530U", "ram": "8GB DDR4",
                               "storage": "256GB SSD", "display": "14\" FHD IPS",
                               "battery": "57Wh", "weight_kg": 1.64, "os": "Windows 11 Home"}}},
    {"catalog_name": "Laptop Văn phòng", "subcategory": "laptop",
     "name": "LG Gram 14 2024", "price": 29990000, "stock": 10,
     "description": "Laptop siêu nhẹ chỉ 980g, pin 72Wh, chứng nhận MIL-STD-810H.",
     "electronics": {"brand": "LG", "warranty_months": 12,
                     "specs": {"cpu": "Intel Core Ultra 7 155H", "ram": "16GB LPDDR5",
                               "storage": "512GB SSD", "display": "14\" WUXGA IPS",
                               "battery": "72Wh", "weight_kg": 0.98, "os": "Windows 11 Home"}}},
    {"catalog_name": "Laptop Văn phòng", "subcategory": "laptop",
     "name": "Samsung Galaxy Book4 Pro 360", "price": 35990000, "stock": 7,
     "description": "Laptop 2-in-1 Samsung, màn hình AMOLED 3K, bút S Pen đi kèm.",
     "electronics": {"brand": "Samsung", "warranty_months": 12,
                     "specs": {"cpu": "Intel Core Ultra 7 155H", "ram": "16GB LPDDR5",
                               "storage": "512GB SSD", "display": "16\" 3K AMOLED Touch",
                               "battery": "76Wh", "weight_kg": 1.66, "os": "Windows 11 Home"}}},
    {"catalog_name": "Laptop Văn phòng", "subcategory": "laptop",
     "name": "ASUS ZenBook 14 OLED UX3405", "price": 26990000, "stock": 12,
     "description": "ZenBook 14 OLED siêu mỏng, chip Intel Core Ultra, màn OLED 3K.",
     "electronics": {"brand": "ASUS", "warranty_months": 12,
                     "specs": {"cpu": "Intel Core Ultra 5 125H", "ram": "16GB LPDDR5",
                               "storage": "512GB SSD", "display": "14\" 3K OLED 120Hz",
                               "battery": "75Wh", "weight_kg": 1.2, "os": "Windows 11 Home"}}},

    # ── LAPTOP ĐỒ HỌA ────────────────────────────────────────────────────────
    {"catalog_name": "Laptop Đồ họa", "subcategory": "laptop",
     "name": "ASUS ProArt Studiobook 16 OLED", "price": 45990000, "stock": 6,
     "description": "Laptop đồ họa OLED 4K DCI-P3 100%, Ryzen 9 7945HX.",
     "electronics": {"brand": "ASUS", "warranty_months": 24,
                     "specs": {"cpu": "AMD Ryzen 9 7945HX", "ram": "32GB DDR5",
                               "storage": "1TB SSD", "display": "16\" OLED 4K 60Hz",
                               "gpu": "RTX 4070 8GB", "weight_kg": 2.4, "os": "Windows 11 Pro"}}},
    {"catalog_name": "Laptop Đồ họa", "subcategory": "laptop",
     "name": "Dell Precision 5680 Workstation", "price": 58990000, "stock": 4,
     "description": "Workstation mobile Dell, NVIDIA RTX A2000, chuẩn ISV.",
     "electronics": {"brand": "Dell", "warranty_months": 36,
                     "specs": {"cpu": "Intel Core i9-13900H", "ram": "32GB DDR5",
                               "storage": "1TB SSD", "display": "16\" FHD+ IPS 60Hz",
                               "gpu": "NVIDIA RTX A2000 8GB", "weight_kg": 1.86, "os": "Windows 11 Pro"}}},
    {"catalog_name": "Laptop Đồ họa", "subcategory": "laptop",
     "name": "HP ZBook Fury 16 G10", "price": 65990000, "stock": 3,
     "description": "Mobile workstation HP cao cấp nhất, RTX 3000 Ada.",
     "electronics": {"brand": "HP", "warranty_months": 36,
                     "specs": {"cpu": "Intel Core i9-13950HX", "ram": "64GB DDR5",
                               "storage": "2TB SSD", "display": "16\" 4K DreamColor IPS",
                               "gpu": "NVIDIA RTX 3000 Ada 12GB", "weight_kg": 2.99, "os": "Windows 11 Pro"}}},
    {"catalog_name": "Laptop Đồ họa", "subcategory": "laptop",
     "name": "MSI Creator Z16P B12UGST", "price": 52990000, "stock": 5,
     "description": "MSI Creator laptop OLED 4K, dành cho video editor và 3D artist.",
     "electronics": {"brand": "MSI", "warranty_months": 12,
                     "specs": {"cpu": "Intel Core i9-12900H", "ram": "32GB DDR5",
                               "storage": "2TB SSD", "display": "16\" 4K OLED 60Hz",
                               "gpu": "RTX 3080 Ti 16GB", "weight_kg": 2.3, "os": "Windows 11 Pro"}}},
    {"catalog_name": "Laptop Đồ họa", "subcategory": "laptop",
     "name": "Razer Blade 16 Studio 2024", "price": 72990000, "stock": 3,
     "description": "Razer Blade 16 màn OLED 4K 120Hz, RTX 4090 cho creator đỉnh cao.",
     "electronics": {"brand": "Razer", "warranty_months": 12,
                     "specs": {"cpu": "Intel Core i9-14900HX", "ram": "32GB DDR5",
                               "storage": "2TB SSD", "display": "16\" 4K OLED 120Hz",
                               "gpu": "RTX 4090 16GB", "weight_kg": 2.47, "os": "Windows 11 Home"}}},

    # ── LAPTOP SINH VIÊN ─────────────────────────────────────────────────────
    {"catalog_name": "Laptop Sinh viên", "subcategory": "laptop",
     "name": "Acer Aspire 3 A315-58", "price": 10990000, "stock": 35,
     "description": "Laptop sinh viên giá rẻ, đủ dùng học tập văn phòng.",
     "electronics": {"brand": "Acer", "warranty_months": 12,
                     "specs": {"cpu": "Intel Core i3-1115G4", "ram": "8GB DDR4",
                               "storage": "256GB SSD", "display": "15.6\" FHD IPS",
                               "battery": "41.4Wh", "weight_kg": 1.7, "os": "Windows 11 Home"}}},
    {"catalog_name": "Laptop Sinh viên", "subcategory": "laptop",
     "name": "Acer Aspire 5 A515-58M", "price": 14990000, "stock": 28,
     "description": "Acer Aspire 5 tầm trung, Core i5 Gen 13, màn 15.6\" FHD.",
     "electronics": {"brand": "Acer", "warranty_months": 12,
                     "specs": {"cpu": "Intel Core i5-1335U", "ram": "8GB DDR4",
                               "storage": "512GB SSD", "display": "15.6\" FHD IPS",
                               "battery": "50Wh", "weight_kg": 1.8, "os": "Windows 11 Home"}}},
    {"catalog_name": "Laptop Sinh viên", "subcategory": "laptop",
     "name": "ASUS Vivobook 15 X1502ZA", "price": 14990000, "stock": 28,
     "description": "ASUS Vivobook thiết kế đẹp, giá tốt cho sinh viên.",
     "electronics": {"brand": "ASUS", "warranty_months": 12,
                     "specs": {"cpu": "Intel Core i5-12500H", "ram": "16GB DDR4",
                               "storage": "512GB SSD", "display": "15.6\" FHD IPS",
                               "battery": "42Wh", "weight_kg": 1.7, "os": "Windows 11 Home"}}},
    {"catalog_name": "Laptop Sinh viên", "subcategory": "laptop",
     "name": "ASUS Vivobook 14X OLED K3405", "price": 18990000, "stock": 20,
     "description": "Vivobook OLED 14 inch sắc nét, Core i5 Gen 13.",
     "electronics": {"brand": "ASUS", "warranty_months": 12,
                     "specs": {"cpu": "Intel Core i5-13500H", "ram": "16GB DDR4",
                               "storage": "512GB SSD", "display": "14\" 2.8K OLED 120Hz",
                               "battery": "70Wh", "weight_kg": 1.5, "os": "Windows 11 Home"}}},
    {"catalog_name": "Laptop Sinh viên", "subcategory": "laptop",
     "name": "Lenovo IdeaPad 3 15IAU7", "price": 11990000, "stock": 30,
     "description": "IdeaPad 3 bàn phím thoải mái, phù hợp học tập hàng ngày.",
     "electronics": {"brand": "Lenovo", "warranty_months": 12,
                     "specs": {"cpu": "Intel Core i5-1235U", "ram": "8GB DDR4",
                               "storage": "256GB SSD", "display": "15.6\" FHD IPS",
                               "battery": "38Wh", "weight_kg": 1.65, "os": "Windows 11 Home"}}},
    {"catalog_name": "Laptop Sinh viên", "subcategory": "laptop",
     "name": "Lenovo IdeaPad Slim 5 16ABR8", "price": 17990000, "stock": 22,
     "description": "IdeaPad Slim 5 màn 16 inch, Ryzen 5, nhẹ chỉ 1.76kg.",
     "electronics": {"brand": "Lenovo", "warranty_months": 12,
                     "specs": {"cpu": "AMD Ryzen 5 7530U", "ram": "16GB DDR4",
                               "storage": "512GB SSD", "display": "16\" WUXGA IPS",
                               "battery": "60Wh", "weight_kg": 1.76, "os": "Windows 11 Home"}}},
    {"catalog_name": "Laptop Sinh viên", "subcategory": "laptop",
     "name": "HP 15s-fq5206TU", "price": 12990000, "stock": 30,
     "description": "HP 15s mỏng nhẹ, Core i5, phù hợp sinh viên các ngành.",
     "electronics": {"brand": "HP", "warranty_months": 12,
                     "specs": {"cpu": "Intel Core i5-1235U", "ram": "8GB DDR4",
                               "storage": "512GB SSD", "display": "15.6\" FHD IPS",
                               "battery": "41Wh", "weight_kg": 1.69, "os": "Windows 11 Home"}}},
    {"catalog_name": "Laptop Sinh viên", "subcategory": "laptop",
     "name": "HP 240 G9 Notebook", "price": 9990000, "stock": 40,
     "description": "HP 240 G9 giá rẻ nhất, phù hợp sinh viên cần laptop cơ bản.",
     "electronics": {"brand": "HP", "warranty_months": 12,
                     "specs": {"cpu": "Intel Core i3-1215U", "ram": "8GB DDR4",
                               "storage": "256GB SSD", "display": "14\" FHD IPS",
                               "battery": "41Wh", "weight_kg": 1.45, "os": "Windows 11 Home"}}},

    # ── MACBOOK ───────────────────────────────────────────────────────────────
    {"catalog_name": "MacBook", "subcategory": "laptop",
     "name": "MacBook Air M2 13\" 8GB/256GB", "price": 24990000, "stock": 25,
     "description": "MacBook Air M2 cơ bản, nhẹ 1.24kg, pin 18 giờ.",
     "electronics": {"brand": "Apple", "warranty_months": 12,
                     "specs": {"cpu": "Apple M2 8-core", "ram": "8GB Unified",
                               "storage": "256GB SSD", "display": "13.6\" Liquid Retina",
                               "gpu": "8-core GPU", "battery": "52.6Wh",
                               "weight_kg": 1.24, "os": "macOS Sonoma"}}},
    {"catalog_name": "MacBook", "subcategory": "laptop",
     "name": "MacBook Air M2 13\" 8GB/512GB", "price": 27990000, "stock": 20,
     "description": "MacBook Air M2 nâng cấp SSD 512GB, hiệu năng ổn định.",
     "electronics": {"brand": "Apple", "warranty_months": 12,
                     "specs": {"cpu": "Apple M2 8-core", "ram": "8GB Unified",
                               "storage": "512GB SSD", "display": "13.6\" Liquid Retina",
                               "gpu": "10-core GPU", "battery": "52.6Wh",
                               "weight_kg": 1.24, "os": "macOS Sonoma"}}},
    {"catalog_name": "MacBook", "subcategory": "laptop",
     "name": "MacBook Air M3 13\" 8GB/256GB", "price": 28990000, "stock": 20,
     "description": "MacBook Air M3 chip thế hệ mới, nhanh hơn M2 30%.",
     "electronics": {"brand": "Apple", "warranty_months": 12,
                     "specs": {"cpu": "Apple M3 8-core", "ram": "8GB Unified",
                               "storage": "256GB SSD", "display": "13.6\" Liquid Retina",
                               "gpu": "10-core GPU", "battery": "52.6Wh",
                               "weight_kg": 1.24, "os": "macOS Sonoma"}}},
    {"catalog_name": "MacBook", "subcategory": "laptop",
     "name": "MacBook Air M3 15\" 16GB/512GB", "price": 38990000, "stock": 15,
     "description": "MacBook Air 15 inch màn hình lớn, RAM 16GB thoải mái đa nhiệm.",
     "electronics": {"brand": "Apple", "warranty_months": 12,
                     "specs": {"cpu": "Apple M3 8-core", "ram": "16GB Unified",
                               "storage": "512GB SSD", "display": "15.3\" Liquid Retina",
                               "gpu": "10-core GPU", "battery": "66.5Wh",
                               "weight_kg": 1.51, "os": "macOS Sonoma"}}},
    {"catalog_name": "MacBook", "subcategory": "laptop",
     "name": "MacBook Pro M3 Pro 14\" 18GB/512GB", "price": 52990000, "stock": 8,
     "description": "MacBook Pro cho lập trình viên và designer chuyên nghiệp.",
     "electronics": {"brand": "Apple", "warranty_months": 12,
                     "specs": {"cpu": "Apple M3 Pro 11-core", "ram": "18GB Unified",
                               "storage": "512GB SSD", "display": "14.2\" Liquid Retina XDR",
                               "gpu": "14-core GPU", "battery": "72Wh",
                               "weight_kg": 1.61, "os": "macOS Sonoma"}}},
    {"catalog_name": "MacBook", "subcategory": "laptop",
     "name": "MacBook Pro M3 Max 16\" 36GB/1TB", "price": 89990000, "stock": 5,
     "description": "MacBook Pro mạnh nhất, chip M3 Max cho video editing và ML.",
     "electronics": {"brand": "Apple", "warranty_months": 12,
                     "specs": {"cpu": "Apple M3 Max 14-core", "ram": "36GB Unified",
                               "storage": "1TB SSD", "display": "16.2\" Liquid Retina XDR",
                               "gpu": "40-core GPU", "battery": "100Wh",
                               "weight_kg": 2.15, "os": "macOS Sonoma"}}},

    # ── ĐIỆN THOẠI ────────────────────────────────────────────────────────────
    # Samsung Galaxy S series
    {"catalog_name": "Điện thoại", "subcategory": "phone",
     "name": "Samsung Galaxy S24 Ultra 12GB/256GB", "price": 31990000, "stock": 20,
     "description": "Flagship Samsung S24 Ultra, S Pen, camera 200MP, AI Galaxy.",
     "electronics": {"brand": "Samsung", "warranty_months": 12,
                     "specs": {"screen": "6.8\" Dynamic AMOLED 2X 120Hz",
                               "ram": "12GB", "storage": "256GB",
                               "camera_main": "200MP + 12MP + 10MP + 10MP",
                               "camera_front": "12MP", "battery": "5000mAh",
                               "os": "Android 14 / One UI 6.1", "sim": "Dual SIM 5G"}}},
    {"catalog_name": "Điện thoại", "subcategory": "phone",
     "name": "Samsung Galaxy S24+ 12GB/256GB", "price": 24990000, "stock": 25,
     "description": "Galaxy S24+ màn hình lớn 6.7\", pin 4900mAh sạc nhanh.",
     "electronics": {"brand": "Samsung", "warranty_months": 12,
                     "specs": {"screen": "6.7\" Dynamic AMOLED 2X 120Hz",
                               "ram": "12GB", "storage": "256GB",
                               "camera_main": "50MP + 10MP + 12MP",
                               "camera_front": "12MP", "battery": "4900mAh",
                               "os": "Android 14 / One UI 6.1", "sim": "Dual SIM 5G"}}},
    {"catalog_name": "Điện thoại", "subcategory": "phone",
     "name": "Samsung Galaxy S24 8GB/128GB", "price": 18990000, "stock": 30,
     "description": "Galaxy S24 nhỏ gọn, chip Exynos 2400, màn 6.2\".",
     "electronics": {"brand": "Samsung", "warranty_months": 12,
                     "specs": {"screen": "6.2\" Dynamic AMOLED 2X 120Hz",
                               "ram": "8GB", "storage": "128GB",
                               "camera_main": "50MP + 10MP + 12MP",
                               "camera_front": "12MP", "battery": "4000mAh",
                               "os": "Android 14 / One UI 6.1", "sim": "Dual SIM 5G"}}},
    {"catalog_name": "Điện thoại", "subcategory": "phone",
     "name": "Samsung Galaxy A55 5G 8GB/128GB", "price": 9490000, "stock": 40,
     "description": "Galaxy A55 tầm trung cao cấp, camera 50MP, thiết kế đẹp.",
     "electronics": {"brand": "Samsung", "warranty_months": 12,
                     "specs": {"screen": "6.6\" Super AMOLED 120Hz",
                               "ram": "8GB", "storage": "128GB",
                               "camera_main": "50MP + 12MP + 5MP",
                               "camera_front": "32MP", "battery": "5000mAh",
                               "os": "Android 14 / One UI 6.1", "sim": "Dual SIM 5G"}}},
    {"catalog_name": "Điện thoại", "subcategory": "phone",
     "name": "Samsung Galaxy A35 5G 8GB/128GB", "price": 7490000, "stock": 50,
     "description": "Galaxy A35 pin 5000mAh, màn Super AMOLED 120Hz giá tốt.",
     "electronics": {"brand": "Samsung", "warranty_months": 12,
                     "specs": {"screen": "6.6\" Super AMOLED 120Hz",
                               "ram": "8GB", "storage": "128GB",
                               "camera_main": "50MP + 8MP + 5MP",
                               "camera_front": "13MP", "battery": "5000mAh",
                               "os": "Android 14 / One UI 6.1", "sim": "Dual SIM 5G"}}},
    {"catalog_name": "Điện thoại", "subcategory": "phone",
     "name": "Samsung Galaxy A15 4G 4GB/128GB", "price": 3990000, "stock": 60,
     "description": "Galaxy A15 giá rẻ nhất dòng A, màn Super AMOLED 90Hz.",
     "electronics": {"brand": "Samsung", "warranty_months": 12,
                     "specs": {"screen": "6.5\" Super AMOLED 90Hz",
                               "ram": "4GB", "storage": "128GB",
                               "camera_main": "50MP + 5MP + 2MP",
                               "camera_front": "13MP", "battery": "5000mAh",
                               "os": "Android 14 / One UI 6", "sim": "Dual SIM 4G"}}},
    # iPhone
    {"catalog_name": "Điện thoại", "subcategory": "phone",
     "name": "iPhone 16 Pro Max 256GB", "price": 34990000, "stock": 15,
     "description": "iPhone 16 Pro Max chip A18 Pro, camera 48MP Tetra Prism, Action Button.",
     "electronics": {"brand": "Apple", "warranty_months": 12,
                     "specs": {"screen": "6.9\" Super Retina XDR OLED ProMotion 120Hz",
                               "ram": "8GB", "storage": "256GB",
                               "camera_main": "48MP + 48MP + 12MP",
                               "camera_front": "12MP", "battery": "4685mAh",
                               "os": "iOS 18", "sim": "Dual SIM eSIM 5G"}}},
    {"catalog_name": "Điện thoại", "subcategory": "phone",
     "name": "iPhone 16 Pro 128GB", "price": 28990000, "stock": 20,
     "description": "iPhone 16 Pro chip A18 Pro, màn 6.3\", camera 48MP.",
     "electronics": {"brand": "Apple", "warranty_months": 12,
                     "specs": {"screen": "6.3\" Super Retina XDR ProMotion 120Hz",
                               "ram": "8GB", "storage": "128GB",
                               "camera_main": "48MP + 48MP + 12MP",
                               "camera_front": "12MP", "battery": "3577mAh",
                               "os": "iOS 18", "sim": "Dual SIM eSIM 5G"}}},
    {"catalog_name": "Điện thoại", "subcategory": "phone",
     "name": "iPhone 16 128GB", "price": 22990000, "stock": 25,
     "description": "iPhone 16 chip A18, hỗ trợ Apple Intelligence, camera 48MP.",
     "electronics": {"brand": "Apple", "warranty_months": 12,
                     "specs": {"screen": "6.1\" Super Retina XDR OLED",
                               "ram": "8GB", "storage": "128GB",
                               "camera_main": "48MP + 12MP",
                               "camera_front": "12MP", "battery": "3561mAh",
                               "os": "iOS 18", "sim": "Dual SIM eSIM 5G"}}},
    {"catalog_name": "Điện thoại", "subcategory": "phone",
     "name": "iPhone 15 128GB", "price": 18990000, "stock": 30,
     "description": "iPhone 15 chip A16, Dynamic Island, USB-C.",
     "electronics": {"brand": "Apple", "warranty_months": 12,
                     "specs": {"screen": "6.1\" Super Retina XDR OLED",
                               "ram": "6GB", "storage": "128GB",
                               "camera_main": "48MP + 12MP",
                               "camera_front": "12MP", "battery": "3349mAh",
                               "os": "iOS 17", "sim": "Dual SIM eSIM 5G"}}},
    {"catalog_name": "Điện thoại", "subcategory": "phone",
     "name": "iPhone 15 Pro 256GB", "price": 27990000, "stock": 18,
     "description": "iPhone 15 Pro chip A17 Pro, khung Titanium, camera 48MP.",
     "electronics": {"brand": "Apple", "warranty_months": 12,
                     "specs": {"screen": "6.1\" ProMotion OLED 120Hz",
                               "ram": "8GB", "storage": "256GB",
                               "camera_main": "48MP + 12MP + 12MP",
                               "camera_front": "12MP", "battery": "3274mAh",
                               "os": "iOS 17", "sim": "Dual SIM eSIM 5G"}}},
    # Xiaomi / Redmi
    {"catalog_name": "Điện thoại", "subcategory": "phone",
     "name": "Xiaomi 14 Ultra 16GB/512GB", "price": 23990000, "stock": 12,
     "description": "Xiaomi 14 Ultra camera Leica 1\" sensor, Snapdragon 8 Gen 3.",
     "electronics": {"brand": "Xiaomi", "warranty_months": 12,
                     "specs": {"screen": "6.73\" LTPO AMOLED 120Hz",
                               "ram": "16GB", "storage": "512GB",
                               "camera_main": "50MP Leica + 50MP + 50MP + 50MP",
                               "camera_front": "32MP", "battery": "5000mAh",
                               "os": "Android 14 / HyperOS", "sim": "Dual SIM 5G"}}},
    {"catalog_name": "Điện thoại", "subcategory": "phone",
     "name": "Xiaomi 14 12GB/256GB", "price": 16990000, "stock": 18,
     "description": "Xiaomi 14 nhỏ gọn, Snapdragon 8 Gen 3, camera Leica.",
     "electronics": {"brand": "Xiaomi", "warranty_months": 12,
                     "specs": {"screen": "6.36\" LTPO AMOLED 120Hz",
                               "ram": "12GB", "storage": "256GB",
                               "camera_main": "50MP Leica + 50MP + 50MP",
                               "camera_front": "32MP", "battery": "4610mAh",
                               "os": "Android 14 / HyperOS", "sim": "Dual SIM 5G"}}},
    {"catalog_name": "Điện thoại", "subcategory": "phone",
     "name": "Redmi Note 13 Pro+ 5G 12GB/256GB", "price": 8990000, "stock": 35,
     "description": "Redmi Note 13 Pro+ camera 200MP, sạc nhanh 120W.",
     "electronics": {"brand": "Xiaomi", "warranty_months": 12,
                     "specs": {"screen": "6.67\" AMOLED 120Hz",
                               "ram": "12GB", "storage": "256GB",
                               "camera_main": "200MP + 8MP + 2MP",
                               "camera_front": "16MP", "battery": "5000mAh",
                               "os": "Android 13 / MIUI 14", "sim": "Dual SIM 5G"}}},
    {"catalog_name": "Điện thoại", "subcategory": "phone",
     "name": "Redmi Note 13 4G 8GB/256GB", "price": 5490000, "stock": 50,
     "description": "Redmi Note 13 camera 108MP, màn AMOLED 120Hz, pin 5000mAh.",
     "electronics": {"brand": "Xiaomi", "warranty_months": 12,
                     "specs": {"screen": "6.67\" AMOLED 120Hz",
                               "ram": "8GB", "storage": "256GB",
                               "camera_main": "108MP + 8MP + 2MP",
                               "camera_front": "16MP", "battery": "5000mAh",
                               "os": "Android 13 / MIUI 14", "sim": "Dual SIM 4G"}}},
    {"catalog_name": "Điện thoại", "subcategory": "phone",
     "name": "Redmi 13C 4GB/128GB", "price": 2990000, "stock": 70,
     "description": "Redmi 13C giá rẻ nhất, pin 5000mAh, camera AI 50MP.",
     "electronics": {"brand": "Xiaomi", "warranty_months": 12,
                     "specs": {"screen": "6.74\" IPS LCD 90Hz",
                               "ram": "4GB", "storage": "128GB",
                               "camera_main": "50MP + 2MP",
                               "camera_front": "8MP", "battery": "5000mAh",
                               "os": "Android 13 / MIUI 14", "sim": "Dual SIM 4G"}}},
    # OPPO
    {"catalog_name": "Điện thoại", "subcategory": "phone",
     "name": "OPPO Find X7 Ultra 16GB/512GB", "price": 22990000, "stock": 10,
     "description": "OPPO Find X7 Ultra camera Hasselblad, Snapdragon 8 Gen 3.",
     "electronics": {"brand": "OPPO", "warranty_months": 12,
                     "specs": {"screen": "6.82\" LTPO AMOLED 120Hz",
                               "ram": "16GB", "storage": "512GB",
                               "camera_main": "50MP Hasselblad + 50MP + 50MP + 50MP",
                               "camera_front": "32MP", "battery": "5000mAh",
                               "os": "Android 14 / ColorOS 14", "sim": "Dual SIM 5G"}}},
    {"catalog_name": "Điện thoại", "subcategory": "phone",
     "name": "OPPO Reno 11 Pro 5G 12GB/256GB", "price": 10990000, "stock": 25,
     "description": "OPPO Reno 11 Pro thiết kế đẹp, camera chân dung 50MP.",
     "electronics": {"brand": "OPPO", "warranty_months": 12,
                     "specs": {"screen": "6.7\" LTPO AMOLED 120Hz",
                               "ram": "12GB", "storage": "256GB",
                               "camera_main": "50MP + 32MP + 8MP",
                               "camera_front": "32MP", "battery": "4600mAh",
                               "os": "Android 14 / ColorOS 14", "sim": "Dual SIM 5G"}}},
    {"catalog_name": "Điện thoại", "subcategory": "phone",
     "name": "OPPO A79 5G 8GB/256GB", "price": 5990000, "stock": 45,
     "description": "OPPO A79 5G tầm trung pin 5000mAh, sạc nhanh 33W.",
     "electronics": {"brand": "OPPO", "warranty_months": 12,
                     "specs": {"screen": "6.72\" IPS LCD 90Hz",
                               "ram": "8GB", "storage": "256GB",
                               "camera_main": "50MP + 2MP",
                               "camera_front": "8MP", "battery": "5000mAh",
                               "os": "Android 13 / ColorOS 13", "sim": "Dual SIM 5G"}}},
    # Vivo
    {"catalog_name": "Điện thoại", "subcategory": "phone",
     "name": "Vivo X100 Pro 16GB/512GB", "price": 22990000, "stock": 10,
     "description": "Vivo X100 Pro camera Zeiss, chip Dimensity 9300.",
     "electronics": {"brand": "Vivo", "warranty_months": 12,
                     "specs": {"screen": "6.78\" LTPO AMOLED 120Hz",
                               "ram": "16GB", "storage": "512GB",
                               "camera_main": "50MP Zeiss + 50MP + 64MP",
                               "camera_front": "32MP", "battery": "5400mAh",
                               "os": "Android 14 / OriginOS 4", "sim": "Dual SIM 5G"}}},
    {"catalog_name": "Điện thoại", "subcategory": "phone",
     "name": "Vivo V30e 5G 8GB/256GB", "price": 6990000, "stock": 35,
     "description": "Vivo V30e thiết kế mỏng nhẹ, camera chân dung AI.",
     "electronics": {"brand": "Vivo", "warranty_months": 12,
                     "specs": {"screen": "6.67\" AMOLED 120Hz",
                               "ram": "8GB", "storage": "256GB",
                               "camera_main": "50MP + 8MP",
                               "camera_front": "50MP", "battery": "5500mAh",
                               "os": "Android 14 / FunTouch OS 14", "sim": "Dual SIM 5G"}}},
    # Realme
    {"catalog_name": "Điện thoại", "subcategory": "phone",
     "name": "Realme GT6 12GB/256GB", "price": 10490000, "stock": 20,
     "description": "Realme GT6 chip Snapdragon 8s Gen 3, màn AMOLED 120Hz.",
     "electronics": {"brand": "Realme", "warranty_months": 12,
                     "specs": {"screen": "6.78\" AMOLED 120Hz",
                               "ram": "12GB", "storage": "256GB",
                               "camera_main": "50MP + 8MP + 2MP",
                               "camera_front": "16MP", "battery": "5500mAh",
                               "os": "Android 14 / realme UI 5", "sim": "Dual SIM 5G"}}},
    {"catalog_name": "Điện thoại", "subcategory": "phone",
     "name": "Realme C67 4G 8GB/256GB", "price": 3990000, "stock": 60,
     "description": "Realme C67 giá tốt, camera 108MP, thiết kế vân da đẹp.",
     "electronics": {"brand": "Realme", "warranty_months": 12,
                     "specs": {"screen": "6.72\" IPS LCD 90Hz",
                               "ram": "8GB", "storage": "256GB",
                               "camera_main": "108MP + 2MP",
                               "camera_front": "8MP", "battery": "5000mAh",
                               "os": "Android 13 / realme UI 4", "sim": "Dual SIM 4G"}}},
    # OnePlus
    {"catalog_name": "Điện thoại", "subcategory": "phone",
     "name": "OnePlus 12 16GB/512GB", "price": 19990000, "stock": 15,
     "description": "OnePlus 12 camera Hasselblad, sạc 100W nhanh nhất phân khúc.",
     "electronics": {"brand": "OnePlus", "warranty_months": 12,
                     "specs": {"screen": "6.82\" LTPO AMOLED 120Hz",
                               "ram": "16GB", "storage": "512GB",
                               "camera_main": "50MP Hasselblad + 48MP + 64MP",
                               "camera_front": "32MP", "battery": "5400mAh",
                               "os": "Android 14 / OxygenOS 14", "sim": "Dual SIM 5G"}}},

    # ── TAI NGHE BLUETOOTH ───────────────────────────────────────────────────
    # Sony
    {"catalog_name": "Tai nghe Bluetooth", "subcategory": "headphone",
     "name": "Sony WH-1000XM5 Over-ear ANC", "price": 6990000, "stock": 25,
     "description": "Tai nghe chống ồn tốt nhất Sony, pin 30h, âm thanh LDAC.",
     "electronics": {"brand": "Sony", "warranty_months": 12,
                     "specs": {"type": "Over-ear", "connectivity": "Bluetooth 5.2",
                               "anc": True, "driver_size": "30mm",
                               "frequency": "4Hz–40kHz", "battery_life_h": 30,
                               "charging": "USB-C", "weight_g": 250}}},
    {"catalog_name": "Tai nghe Bluetooth", "subcategory": "headphone",
     "name": "Sony WF-1000XM5 True Wireless", "price": 5990000, "stock": 30,
     "description": "TWS premium Sony, chip V2 chống ồn, Bluetooth Multipoint.",
     "electronics": {"brand": "Sony", "warranty_months": 12,
                     "specs": {"type": "In-ear TWS", "connectivity": "Bluetooth 5.3",
                               "anc": True, "driver_size": "8.4mm",
                               "frequency": "20Hz–20kHz", "battery_life_h": 8,
                               "battery_case_h": 24, "charging": "USB-C + Wireless",
                               "weight_g": 5.9}}},
    {"catalog_name": "Tai nghe Bluetooth", "subcategory": "headphone",
     "name": "Sony WH-CH720N Over-ear Lite ANC", "price": 2990000, "stock": 40,
     "description": "Sony CH720N ANC nhẹ chỉ 192g, pin 35h, giá tầm trung.",
     "electronics": {"brand": "Sony", "warranty_months": 12,
                     "specs": {"type": "Over-ear", "connectivity": "Bluetooth 5.2",
                               "anc": True, "battery_life_h": 35,
                               "charging": "USB-C", "weight_g": 192}}},
    {"catalog_name": "Tai nghe Bluetooth", "subcategory": "headphone",
     "name": "Sony LinkBuds S True Wireless ANC", "price": 3490000, "stock": 35,
     "description": "LinkBuds S nhỏ nhất Sony, đeo thoải mái, Speak-to-Chat.",
     "electronics": {"brand": "Sony", "warranty_months": 12,
                     "specs": {"type": "In-ear TWS", "connectivity": "Bluetooth 5.2",
                               "anc": True, "battery_life_h": 6,
                               "battery_case_h": 14, "charging": "USB-C + Wireless",
                               "weight_g": 4.8}}},
    # Bose
    {"catalog_name": "Tai nghe Bluetooth", "subcategory": "headphone",
     "name": "Bose QuietComfort Ultra Headphones", "price": 8990000, "stock": 15,
     "description": "Tai nghe ANC đỉnh cao Bose, Immersive Audio, pin 24h.",
     "electronics": {"brand": "Bose", "warranty_months": 12,
                     "specs": {"type": "Over-ear", "connectivity": "Bluetooth 5.3",
                               "anc": True, "battery_life_h": 24,
                               "charging": "USB-C", "weight_g": 250}}},
    {"catalog_name": "Tai nghe Bluetooth", "subcategory": "headphone",
     "name": "Bose QuietComfort Ultra Earbuds", "price": 7490000, "stock": 18,
     "description": "Bose QC Ultra Earbuds ANC chuẩn, Immersive Audio 3D.",
     "electronics": {"brand": "Bose", "warranty_months": 12,
                     "specs": {"type": "In-ear TWS", "connectivity": "Bluetooth 5.3",
                               "anc": True, "battery_life_h": 6,
                               "battery_case_h": 24, "charging": "USB-C + Wireless",
                               "weight_g": 6.2}}},
    {"catalog_name": "Tai nghe Bluetooth", "subcategory": "headphone",
     "name": "Bose QuietComfort 45", "price": 5990000, "stock": 20,
     "description": "Bose QC45 ANC thoải mái đeo cả ngày, pin 24h.",
     "electronics": {"brand": "Bose", "warranty_months": 12,
                     "specs": {"type": "Over-ear", "connectivity": "Bluetooth 5.1",
                               "anc": True, "battery_life_h": 24,
                               "charging": "USB-C", "weight_g": 238}}},
    # Apple
    {"catalog_name": "Tai nghe Bluetooth", "subcategory": "headphone",
     "name": "Apple AirPods Pro (2nd Gen) USB-C", "price": 5990000, "stock": 30,
     "description": "AirPods Pro 2 ANC H2 chip, Adaptive Audio, sạc USB-C.",
     "electronics": {"brand": "Apple", "warranty_months": 12,
                     "specs": {"type": "In-ear TWS", "connectivity": "Bluetooth 5.3",
                               "anc": True, "battery_life_h": 6,
                               "battery_case_h": 30, "charging": "USB-C + MagSafe",
                               "weight_g": 5.3}}},
    {"catalog_name": "Tai nghe Bluetooth", "subcategory": "headphone",
     "name": "Apple AirPods 4 Active Noise Cancellation", "price": 3990000, "stock": 35,
     "description": "AirPods 4 ANC, thiết kế mới không dây sạc, Transparency mode.",
     "electronics": {"brand": "Apple", "warranty_months": 12,
                     "specs": {"type": "In-ear TWS", "connectivity": "Bluetooth 5.3",
                               "anc": True, "battery_life_h": 5,
                               "battery_case_h": 30, "charging": "USB-C",
                               "weight_g": 4.3}}},
    {"catalog_name": "Tai nghe Bluetooth", "subcategory": "headphone",
     "name": "Apple AirPods Max Space Gray", "price": 12990000, "stock": 10,
     "description": "AirPods Max over-ear, ANC 9 mic, dây đan Mesh, USB-C.",
     "electronics": {"brand": "Apple", "warranty_months": 12,
                     "specs": {"type": "Over-ear", "connectivity": "Bluetooth 5.3",
                               "anc": True, "driver_size": "40mm",
                               "battery_life_h": 20, "charging": "USB-C",
                               "weight_g": 385}}},
    # JBL
    {"catalog_name": "Tai nghe Bluetooth", "subcategory": "headphone",
     "name": "JBL Tour One M2 Over-ear ANC", "price": 4490000, "stock": 25,
     "description": "JBL Tour One M2 ANC 4-mic, pin 30h, Multipoint kép.",
     "electronics": {"brand": "JBL", "warranty_months": 12,
                     "specs": {"type": "Over-ear", "connectivity": "Bluetooth 5.3",
                               "anc": True, "driver_size": "40mm",
                               "battery_life_h": 30, "charging": "USB-C",
                               "weight_g": 254}}},
    {"catalog_name": "Tai nghe Bluetooth", "subcategory": "headphone",
     "name": "JBL Live 660NC Wireless", "price": 2490000, "stock": 40,
     "description": "JBL Live 660NC ANC 50h, JBL Signature Sound, Voice Assistant.",
     "electronics": {"brand": "JBL", "warranty_months": 12,
                     "specs": {"type": "Over-ear", "connectivity": "Bluetooth 5.0",
                               "anc": True, "battery_life_h": 50,
                               "charging": "USB-C", "weight_g": 220}}},
    {"catalog_name": "Tai nghe Bluetooth", "subcategory": "headphone",
     "name": "JBL Tune Buds True Wireless ANC", "price": 1490000, "stock": 55,
     "description": "JBL Tune Buds ANC giá tốt nhất, pin 48h với hộp sạc.",
     "electronics": {"brand": "JBL", "warranty_months": 12,
                     "specs": {"type": "In-ear TWS", "connectivity": "Bluetooth 5.3",
                               "anc": True, "battery_life_h": 10,
                               "battery_case_h": 48, "charging": "USB-C",
                               "weight_g": 5}}},
    {"catalog_name": "Tai nghe Bluetooth", "subcategory": "headphone",
     "name": "JBL Wave Beam True Wireless", "price": 890000, "stock": 70,
     "description": "JBL Wave Beam pin 32h, chống nước IPX5, giá cực tốt.",
     "electronics": {"brand": "JBL", "warranty_months": 12,
                     "specs": {"type": "In-ear TWS", "connectivity": "Bluetooth 5.2",
                               "anc": False, "battery_life_h": 8,
                               "battery_case_h": 32, "charging": "USB-C",
                               "weight_g": 5}}},
    # Anker Soundcore
    {"catalog_name": "Tai nghe Bluetooth", "subcategory": "headphone",
     "name": "Anker Soundcore Space Q45 ANC", "price": 1990000, "stock": 45,
     "description": "Soundcore Q45 ANC 50h giá rẻ, LDAC Hi-Res Audio.",
     "electronics": {"brand": "Anker", "warranty_months": 12,
                     "specs": {"type": "Over-ear", "connectivity": "Bluetooth 5.3",
                               "anc": True, "battery_life_h": 50,
                               "charging": "USB-C", "weight_g": 253}}},
    {"catalog_name": "Tai nghe Bluetooth", "subcategory": "headphone",
     "name": "Anker Soundcore Liberty 4 NC TWS", "price": 1490000, "stock": 50,
     "description": "Liberty 4 NC ANC 10 mic, LDAC, pin 50h tổng.",
     "electronics": {"brand": "Anker", "warranty_months": 12,
                     "specs": {"type": "In-ear TWS", "connectivity": "Bluetooth 5.3",
                               "anc": True, "battery_life_h": 10,
                               "battery_case_h": 50, "charging": "USB-C + Wireless",
                               "weight_g": 5.3}}},
    # Samsung
    {"catalog_name": "Tai nghe Bluetooth", "subcategory": "headphone",
     "name": "Samsung Galaxy Buds3 Pro TWS ANC", "price": 4990000, "stock": 20,
     "description": "Galaxy Buds3 Pro ANC 360 Audio, thiết kế open-type mới.",
     "electronics": {"brand": "Samsung", "warranty_months": 12,
                     "specs": {"type": "In-ear TWS", "connectivity": "Bluetooth 5.4",
                               "anc": True, "battery_life_h": 6,
                               "battery_case_h": 26, "charging": "USB-C + Wireless",
                               "weight_g": 5.5}}},
    {"catalog_name": "Tai nghe Bluetooth", "subcategory": "headphone",
     "name": "Samsung Galaxy Buds FE TWS", "price": 1990000, "stock": 40,
     "description": "Galaxy Buds FE ANC giá tầm trung, ergonomic fit.",
     "electronics": {"brand": "Samsung", "warranty_months": 12,
                     "specs": {"type": "In-ear TWS", "connectivity": "Bluetooth 5.2",
                               "anc": True, "battery_life_h": 6,
                               "battery_case_h": 21, "charging": "USB-C",
                               "weight_g": 5.6}}},
    # Sennheiser
    {"catalog_name": "Tai nghe Bluetooth", "subcategory": "headphone",
     "name": "Sennheiser MOMENTUM 4 Wireless", "price": 6490000, "stock": 12,
     "description": "Sennheiser Momentum 4 ANC, âm thanh audiophile, pin 60h.",
     "electronics": {"brand": "Sennheiser", "warranty_months": 24,
                     "specs": {"type": "Over-ear", "connectivity": "Bluetooth 5.2",
                               "anc": True, "driver_size": "42mm",
                               "frequency": "6Hz–22kHz", "battery_life_h": 60,
                               "charging": "USB-C", "weight_g": 293}}},
    {"catalog_name": "Tai nghe Bluetooth", "subcategory": "headphone",
     "name": "Sennheiser CX True Wireless Plus", "price": 2990000, "stock": 25,
     "description": "Sennheiser CX Plus ANC, 27h pin, âm thanh trung thực.",
     "electronics": {"brand": "Sennheiser", "warranty_months": 24,
                     "specs": {"type": "In-ear TWS", "connectivity": "Bluetooth 5.2",
                               "anc": True, "battery_life_h": 9,
                               "battery_case_h": 27, "charging": "USB-C",
                               "weight_g": 5}}},
]

# ─────────────────────────────────────────────────────────────────────────────
# THỜI TRANG
# ─────────────────────────────────────────────────────────────────────────────
FASHION_DATA = [
    # Áo nam
    {"catalog_name": "Áo nam",
     "name": "Áo thun nam basic cotton trắng", "price": 149000, "stock": 100,
     "description": "Áo thun nam form regular, cotton 100% thoáng mát.",
     "fashion": {"brand": "Local Brand VN", "sizes": ["S", "M", "L", "XL", "XXL"],
                 "colors": ["Trắng", "Đen", "Xám"], "material": "100% Cotton", "gender": "male"}},
    {"catalog_name": "Áo nam",
     "name": "Áo polo nam Lacoste slim fit", "price": 890000, "stock": 30,
     "description": "Áo polo nam Lacoste chính hãng, chất vải piqué cao cấp.",
     "fashion": {"brand": "Lacoste", "sizes": ["M", "L", "XL"],
                 "colors": ["Xanh navy", "Trắng", "Đỏ"], "material": "Piqué cotton", "gender": "male"}},
    {"catalog_name": "Áo nam",
     "name": "Áo sơ mi nam Oxford trắng form regular", "price": 350000, "stock": 50,
     "description": "Áo sơ mi nam form regular, vải Oxford chống nhăn.",
     "fashion": {"brand": "Owen", "sizes": ["S", "M", "L", "XL"],
                 "colors": ["Trắng", "Xanh nhạt"], "material": "Cotton Oxford", "gender": "male"}},
    {"catalog_name": "Áo nam",
     "name": "Áo thun in logo Adidas Originals", "price": 450000, "stock": 60,
     "description": "Áo thun Adidas Original, chất cotton pha spandex co giãn.",
     "fashion": {"brand": "Adidas", "sizes": ["S", "M", "L", "XL", "XXL"],
                 "colors": ["Đen", "Trắng", "Xanh navy"], "material": "Cotton pha Spandex", "gender": "male"}},
    {"catalog_name": "Áo nam",
     "name": "Áo hoodie nam unisex oversize", "price": 399000, "stock": 75,
     "description": "Áo hoodie form oversize, vải nỉ dày ấm áp, dây kéo tiện lợi.",
     "fashion": {"brand": "YODY", "sizes": ["S", "M", "L", "XL", "XXL"],
                 "colors": ["Đen", "Xám", "Kem"], "material": "Cotton French Terry",
                 "gender": "male", "season": "Đông"}},
    {"catalog_name": "Áo nam",
     "name": "Áo khoác dù nam chống nước", "price": 599000, "stock": 40,
     "description": "Áo khoác dù chống nước nhẹ, gấp gọn vào túi.",
     "fashion": {"brand": "Columbia", "sizes": ["S", "M", "L", "XL"],
                 "colors": ["Đen", "Xanh rêu", "Cam"], "material": "Nylon chống nước",
                 "gender": "male", "season": "Đông"}},
    # Quần nam
    {"catalog_name": "Quần nam",
     "name": "Quần jean nam slim fit xanh đậm", "price": 399000, "stock": 70,
     "description": "Quần jean nam form slim, vải denim co giãn thoải mái.",
     "fashion": {"brand": "Routine", "sizes": ["28", "29", "30", "31", "32", "34"],
                 "colors": ["Xanh đậm", "Xanh nhạt", "Đen"], "material": "Denim co giãn", "gender": "male"}},
    {"catalog_name": "Quần nam",
     "name": "Quần kaki nam công sở màu be", "price": 299000, "stock": 55,
     "description": "Quần kaki nam màu trơn, phù hợp đi làm và dạo phố.",
     "fashion": {"brand": "An Phước", "sizes": ["28", "29", "30", "31", "32"],
                 "colors": ["Be", "Xám", "Đen", "Nâu"], "material": "Cotton kaki", "gender": "male"}},
    {"catalog_name": "Quần nam",
     "name": "Quần short nam thể thao Nike Dri-FIT", "price": 650000, "stock": 80,
     "description": "Quần short Nike Dri-FIT, thoát mồ hôi nhanh cho thể thao.",
     "fashion": {"brand": "Nike", "sizes": ["S", "M", "L", "XL"],
                 "colors": ["Đen", "Xám", "Xanh navy"], "material": "Polyester Dri-FIT",
                 "gender": "male", "season": "Hè"}},
    {"catalog_name": "Quần nam",
     "name": "Quần jogger nam cotton thu đông", "price": 349000, "stock": 65,
     "description": "Quần jogger nam form tapered, vải cotton nỉ ấm.",
     "fashion": {"brand": "Coolmate", "sizes": ["S", "M", "L", "XL", "XXL"],
                 "colors": ["Đen", "Xám", "Nâu"], "material": "Cotton French Terry",
                 "gender": "male", "season": "Đông"}},
    # Áo nữ
    {"catalog_name": "Áo nữ",
     "name": "Áo blouse nữ cổ V chiffon trắng", "price": 289000, "stock": 65,
     "description": "Áo blouse nữ vải chiffon nhẹ, phù hợp đi làm và dạo phố.",
     "fashion": {"brand": "ZARA", "sizes": ["XS", "S", "M", "L"],
                 "colors": ["Trắng", "Đen", "Hồng pastel"], "material": "Chiffon", "gender": "female"}},
    {"catalog_name": "Áo nữ",
     "name": "Áo thun nữ basic crop top cotton", "price": 165000, "stock": 90,
     "description": "Áo thun nữ form crop, cotton thoáng mát cho mùa hè.",
     "fashion": {"brand": "H&M", "sizes": ["XS", "S", "M", "L", "XL"],
                 "colors": ["Trắng", "Đen", "Hồng", "Xanh mint"],
                 "material": "Cotton 100%", "gender": "female", "season": "Hè"}},
    {"catalog_name": "Áo nữ",
     "name": "Áo sơ mi nữ kẻ sọc nhỏ tay dài", "price": 320000, "stock": 45,
     "description": "Áo sơ mi nữ kẻ sọc tinh tế, vải cotton mềm mịn.",
     "fashion": {"brand": "Owen", "sizes": ["XS", "S", "M", "L"],
                 "colors": ["Trắng sọc xanh", "Trắng sọc đen"], "material": "Cotton", "gender": "female"}},
    {"catalog_name": "Áo nữ",
     "name": "Áo len nữ cổ lọ dáng ôm", "price": 450000, "stock": 40,
     "description": "Áo len nữ cổ lọ form ôm, chất liệu len mềm ấm.",
     "fashion": {"brand": "ZARA", "sizes": ["XS", "S", "M", "L"],
                 "colors": ["Kem", "Trắng", "Đen", "Be"],
                 "material": "Len pha acrylic", "gender": "female", "season": "Đông"}},
    # Quần & Váy nữ
    {"catalog_name": "Quần & Váy nữ",
     "name": "Váy midi hoa nhí nữ tầng tầng", "price": 399000, "stock": 50,
     "description": "Váy midi hoa nhí phong cách boho tiểu thư.",
     "fashion": {"brand": "ZARA", "sizes": ["XS", "S", "M", "L"],
                 "colors": ["Trắng hoa", "Hồng hoa", "Xanh hoa"],
                 "material": "Viscose", "gender": "female", "season": "Hè"}},
    {"catalog_name": "Quần & Váy nữ",
     "name": "Quần jean nữ ống suông cao cấp", "price": 450000, "stock": 60,
     "description": "Quần jean nữ form ống suông, denim cao cấp tôn dáng.",
     "fashion": {"brand": "Levi's", "sizes": ["25", "26", "27", "28", "29"],
                 "colors": ["Xanh trơn", "Xanh wash", "Đen"],
                 "material": "Denim", "gender": "female"}},
    {"catalog_name": "Quần & Váy nữ",
     "name": "Chân váy xếp li kaki midi", "price": 285000, "stock": 55,
     "description": "Chân váy xếp li midi kaki, thanh lịch phù hợp đi làm.",
     "fashion": {"brand": "IFU", "sizes": ["XS", "S", "M", "L"],
                 "colors": ["Be", "Đen", "Xanh navy"],
                 "material": "Kaki", "gender": "female"}},
    {"catalog_name": "Quần & Váy nữ",
     "name": "Váy đầm babydoll tay bồng nữ", "price": 350000, "stock": 45,
     "description": "Váy babydoll tay phồng dễ thương, vải linen nhẹ.",
     "fashion": {"brand": "Rosé Girl", "sizes": ["XS", "S", "M", "L"],
                 "colors": ["Trắng", "Hồng phấn", "Xanh bạc hà"],
                 "material": "Linen", "gender": "female", "season": "Hè"}},
    # Đồ đi biển
    {"catalog_name": "Đồ đi biển",
     "name": "Quần short bơi nam tropical", "price": 199000, "stock": 80,
     "description": "Quần short bơi nam họa tiết nhiệt đới, khô nhanh.",
     "fashion": {"brand": "Speedo", "sizes": ["S", "M", "L", "XL"],
                 "colors": ["Xanh biển", "Cam", "Đen"], "material": "Polyester nhanh khô",
                 "gender": "male", "season": "Hè"}},
    {"catalog_name": "Đồ đi biển",
     "name": "Áo bơi nữ 1 mảnh UPF50+", "price": 350000, "stock": 60,
     "description": "Áo bơi nữ chống nắng UPF50+, vải co giãn 4 chiều.",
     "fashion": {"brand": "Arena", "sizes": ["XS", "S", "M", "L"],
                 "colors": ["Đen", "Xanh navy", "Hồng"], "material": "Nylon Lycra",
                 "gender": "female", "season": "Hè"}},
    {"catalog_name": "Đồ đi biển",
     "name": "Áo sơ mi đi biển unisex linen", "price": 285000, "stock": 70,
     "description": "Áo sơ mi linen thoáng mát, phong cách resort đi biển.",
     "fashion": {"brand": "Routine", "sizes": ["S", "M", "L", "XL", "XXL"],
                 "colors": ["Trắng", "Kem", "Xanh pastel"], "material": "Linen 100%",
                 "gender": "unisex", "season": "Hè"}},
    {"catalog_name": "Đồ đi biển",
     "name": "Set đồ resort nữ áo và quần", "price": 520000, "stock": 40,
     "description": "Set đồ resort 2 món, vải viscose nhẹ mịn cho kỳ nghỉ biển.",
     "fashion": {"brand": "YODY", "sizes": ["S", "M", "L"],
                 "colors": ["Trắng hoa", "Be hoa", "Xanh sọc"], "material": "Viscose",
                 "gender": "female", "season": "Hè"}},
    {"catalog_name": "Đồ đi biển",
     "name": "Kính mát unisex UV400 gọng tròn", "price": 180000, "stock": 100,
     "description": "Kính mát chống tia UV400, gọng nhựa nhẹ, phù hợp đi biển.",
     "fashion": {"brand": "Ray-Ban VN", "sizes": ["Free size"],
                 "colors": ["Đen", "Nâu tortoise", "Xanh biển"],
                 "material": "Nhựa TR90 + Kính Polycarbonate", "gender": "unisex", "season": "Hè"}},
    # Giày dép
    {"catalog_name": "Giày dép",
     "name": "Sneaker Nike Air Force 1 Low trắng", "price": 2490000, "stock": 35,
     "description": "Nike Air Force 1 cổ thấp màu trắng thuần khiết, biểu tượng đường phố.",
     "fashion": {"brand": "Nike", "sizes": ["38", "39", "40", "41", "42", "43", "44"],
                 "colors": ["Trắng"], "material": "Leather tổng hợp",
                 "gender": "unisex"}},
    {"catalog_name": "Giày dép",
     "name": "Sneaker Adidas Ultraboost 22 nam", "price": 3490000, "stock": 25,
     "description": "Adidas Ultraboost 22 đệm Boost êm ái, chạy bộ và thể thao.",
     "fashion": {"brand": "Adidas", "sizes": ["39", "40", "41", "42", "43", "44"],
                 "colors": ["Đen trắng", "Trắng xanh", "Xám"], "material": "Primeknit+",
                 "gender": "male"}},
    {"catalog_name": "Giày dép",
     "name": "Sandal nam da bò handmade nâu", "price": 450000, "stock": 40,
     "description": "Sandal nam da bò thật thủ công, bền đẹp theo thời gian.",
     "fashion": {"brand": "Giày Thủ Công VN", "sizes": ["38", "39", "40", "41", "42", "43"],
                 "colors": ["Nâu", "Đen"], "material": "Da bò thật", "gender": "male"}},
    {"catalog_name": "Giày dép",
     "name": "Dép nữ đế bệt hoa cúc cute", "price": 220000, "stock": 75,
     "description": "Dép nữ đế bệt họa tiết hoa cúc cute, nhẹ nhàng đi hè.",
     "fashion": {"brand": "Bitis", "sizes": ["35", "36", "37", "38", "39"],
                 "colors": ["Trắng", "Be", "Hồng"], "material": "PU cao cấp",
                 "gender": "female", "season": "Hè"}},
    {"catalog_name": "Giày dép",
     "name": "Giày cao gót nữ mũi nhọn 7cm", "price": 599000, "stock": 30,
     "description": "Giày cao gót mũi nhọn 7cm, da PU bóng, thanh lịch công sở.",
     "fashion": {"brand": "T&T Shoes", "sizes": ["35", "36", "37", "38", "39"],
                 "colors": ["Đen", "Nude", "Đỏ"], "material": "Da PU tổng hợp",
                 "gender": "female"}},
    # Phụ kiện thời trang
    {"catalog_name": "Phụ kiện thời trang",
     "name": "Túi tote canvas in chữ phong cách", "price": 185000, "stock": 90,
     "description": "Túi tote vải canvas dày, có túi nhỏ bên trong, nhiều màu.",
     "fashion": {"brand": "Local Brand", "sizes": ["Free size"],
                 "colors": ["Trắng", "Đen", "Kem"], "material": "Canvas 12oz",
                 "gender": "unisex"}},
    {"catalog_name": "Phụ kiện thời trang",
     "name": "Nón bucket hat cotton trơn", "price": 135000, "stock": 120,
     "description": "Nón bucket che nắng thời trang, vải cotton mềm mịn.",
     "fashion": {"brand": "H&M", "sizes": ["Free size"],
                 "colors": ["Đen", "Be", "Xanh navy", "Hồng pastel"],
                 "material": "Cotton 100%", "gender": "unisex", "season": "Hè"}},
    {"catalog_name": "Phụ kiện thời trang",
     "name": "Thắt lưng nam da bò khóa kim", "price": 250000, "stock": 60,
     "description": "Thắt lưng nam da bò thật, khóa kim vàng/bạc sang trọng.",
     "fashion": {"brand": "Mano", "sizes": ["105cm", "110cm", "115cm"],
                 "colors": ["Nâu", "Đen"], "material": "Da bò thật", "gender": "male"}},
]


class Command(BaseCommand):
    help = 'Seed sản phẩm mẫu: sách, đồ điện tử (laptop/điện thoại/tai nghe), thời trang'

    def _get_catalog_map(self):
        try:
            resp = requests.get(f"{CATALOG_SERVICE_URL}/api/catalogs/", timeout=10)
            catalogs = resp.json()
            if isinstance(catalogs, dict):
                catalogs = catalogs.get('results', [])
            return {c['name']: c['id'] for c in catalogs}
        except Exception as e:
            self.stderr.write(f"Không thể lấy catalog list: {e}")
            return {}

    def handle(self, *args, **options):
        catalog_map = self._get_catalog_map()
        if not catalog_map:
            self.stdout.write(self.style.WARNING(
                "Không lấy được catalog list. Dùng catalog_id mặc định."
            ))

        created = 0

        # ── Seed sách ────────────────────────────────────────────────────────
        for data in BOOKS_DATA:
            catalog_id = catalog_map.get(data['catalog_name'], 1)
            product, _ = Product.objects.update_or_create(
                name=data['name'], product_type='book',
                defaults={
                    'catalog_id': catalog_id,
                    'description': data.get('description', ''),
                    'price': data['price'], 'stock': data['stock'],
                    'image_url': data.get('image_url', ''), 'is_active': True,
                }
            )
            Book.objects.update_or_create(product=product, defaults=data['book'])
            created += 1

        # ── Seed đồ điện tử ──────────────────────────────────────────────────
        for data in ELECTRONICS_DATA:
            catalog_id = catalog_map.get(data['catalog_name'], 8)
            product, _ = Product.objects.update_or_create(
                name=data['name'], product_type='electronics',
                defaults={
                    'catalog_id': catalog_id,
                    'description': data.get('description', ''),
                    'price': data['price'], 'stock': data['stock'],
                    'image_url': data.get('image_url', ''), 'is_active': True,
                }
            )
            e = data['electronics']
            Electronics.objects.update_or_create(
                product=product,
                defaults={
                    'brand': e['brand'],
                    'subcategory': data['subcategory'],
                    'specs': e.get('specs', {}),
                    'warranty_months': e.get('warranty_months', 12),
                }
            )
            created += 1

        # ── Seed thời trang ──────────────────────────────────────────────────
        for data in FASHION_DATA:
            catalog_id = catalog_map.get(data['catalog_name'], 14)
            product, _ = Product.objects.update_or_create(
                name=data['name'], product_type='fashion',
                defaults={
                    'catalog_id': catalog_id,
                    'description': data.get('description', ''),
                    'price': data['price'], 'stock': data['stock'],
                    'image_url': data.get('image_url', ''), 'is_active': True,
                }
            )
            Fashion.objects.update_or_create(product=product, defaults=data['fashion'])
            created += 1

        book_count = Product.objects.filter(product_type='book').count()
        elec_count = Product.objects.filter(product_type='electronics').count()
        fashion_count = Product.objects.filter(product_type='fashion').count()
        laptop_count = Electronics.objects.filter(subcategory='laptop').count()
        phone_count = Electronics.objects.filter(subcategory='phone').count()
        headphone_count = Electronics.objects.filter(subcategory='headphone').count()

        self.stdout.write(self.style.SUCCESS(
            f"Seed xong {created} sản phẩm:\n"
            f"  Sách:       {book_count}\n"
            f"  Điện tử:    {elec_count} "
            f"(laptop={laptop_count}, điện thoại={phone_count}, tai nghe={headphone_count})\n"
            f"  Thời trang: {fashion_count}"
        ))
